title: The Need for Reform
author: Migz
email: Imlearning@gmaill.com
description: > # this means to ignore newlines until "baseurl:"
  Let's make this the best blog ever

# social links
twitter_username: testrun # DO NOT include the @ character, or else the build will fail!
github_username:  MigzR20 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
